"""add subdomain to tenant

Revision ID: 0990c9668f8c
Revises: af560e9b3d7a
Create Date: 2026-03-11 23:31:18.989483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0990c9668f8c'
down_revision: Union[str, Sequence[str], None] = 'af560e9b3d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ia_master', sa.Column('max_client_permit', sa.Integer(), server_default='10', nullable=False))
    op.add_column('ia_master', sa.Column('current_client_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('storage_connectors', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('storage_connectors_tenant_id_fkey'), 'storage_connectors', type_='foreignkey')
    op.add_column('tenants', sa.Column('subdomain', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_column('tenants', 'subdomain')
    op.create_foreign_key(op.f('storage_connectors_tenant_id_fkey'), 'storage_connectors', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('storage_connectors', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ia_master', 'current_client_count')
    op.drop_column('ia_master', 'max_client_permit')
    # ### end Alembic commands ###
