"""cleanup_master_db_remove_business_tables

Revision ID: 452092237040
Revises: 4abefd762155
Create Date: 2026-03-24 22:28:52.347102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452092237040'
down_revision: Union[str, Sequence[str], None] = '4abefd762155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added to cleanup master DB
    op.execute("DROP TABLE IF EXISTS client_audit_trail CASCADE")
    op.execute("DROP TABLE IF EXISTS client_documents CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_trail CASCADE")
    op.execute("DROP TABLE IF EXISTS clients CASCADE")
    op.execute("DROP TABLE IF EXISTS employee_details CASCADE")
    op.execute("DROP TABLE IF EXISTS ia_master CASCADE")
    op.execute("DROP TABLE IF EXISTS storage_connectors CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Since these tables were not supposed to be here in the first place, 
    # and they should be managed by the Provisioner for tenants, 
    # we don't necessarily want to recreate them in the Master DB on downgrade.
    pass
