"""add custom_domain to tenant

Revision ID: 4abefd762155
Revises: c1cfad5b9ba8
Create Date: 2026-03-24 22:09:24.400232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abefd762155'
down_revision: Union[str, Sequence[str], None] = 'c1cfad5b9ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('custom_domain', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_custom_domain'), 'tenants', ['custom_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_custom_domain'), table_name='tenants')
    op.drop_column('tenants', 'custom_domain')
    # ### end Alembic commands ###
