"""add_bridge_architecture_fields

Revision ID: 646e63833b7f
Revises: 4abefd762155
Create Date: 2026-04-01 02:16:00.767981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646e63833b7f'
down_revision: Union[str, Sequence[str], None] = '4abefd762155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('access_key_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_secret_key', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('client_count_at_billing', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_records_tenant_id'), 'billing_records', ['tenant_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_tenant_id'), 'token_usage', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('bridge_url', sa.String(length=512), nullable=True))
    op.add_column('tenants', sa.Column('bridge_registration_token', sa.String(length=128), nullable=True))
    op.add_column('tenants', sa.Column('bridge_api_secret', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('bridge_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('tenants', sa.Column('bridge_registered_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('bridge_last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('max_client_permit', sa.Integer(), server_default='5', nullable=False))
    op.add_column('tenants', sa.Column('current_client_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_tenants_bridge_registration_token'), 'tenants', ['bridge_registration_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_bridge_registration_token'), table_name='tenants')
    op.drop_column('tenants', 'current_client_count')
    op.drop_column('tenants', 'max_client_permit')
    op.drop_column('tenants', 'bridge_last_heartbeat')
    op.drop_column('tenants', 'bridge_registered_at')
    op.drop_column('tenants', 'bridge_status')
    op.drop_column('tenants', 'bridge_api_secret')
    op.drop_column('tenants', 'bridge_registration_token')
    op.drop_column('tenants', 'bridge_url')
    op.drop_index(op.f('ix_token_usage_tenant_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_billing_records_tenant_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_table('storage_connectors')
    # ### end Alembic commands ###
