"""Add record_version_control_statement

Revision ID: 689130d5bdfd
Revises: 13b95f292547
Create Date: 2026-04-09 14:21:43.324751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689130d5bdfd'
down_revision: Union[str, Sequence[str], None] = '13b95f292547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iamaster_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_user_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('change_reason_type', sa.String(length=50), nullable=True),
    sa.Column('change_reason_text', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_trail', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('audit_trail', sa.Column('field_changed', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('change_reason_type', sa.String(length=50), nullable=True))
    op.add_column('audit_trail', sa.Column('change_reason_text', sa.Text(), nullable=True))
    op.add_column('audit_trail', sa.Column('entity_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_trail', 'entity_version')
    op.drop_column('audit_trail', 'change_reason_text')
    op.drop_column('audit_trail', 'change_reason_type')
    op.drop_column('audit_trail', 'new_value')
    op.drop_column('audit_trail', 'old_value')
    op.drop_column('audit_trail', 'field_changed')
    op.drop_column('audit_trail', 'user_id')
    op.drop_table('report_history')
    op.drop_table('iamaster_versions')
    # ### end Alembic commands ###
