"""add_assigned_employee_id_to_clients

Revision ID: 77846ec918bd
Revises: b4f2ada8ae10
Create Date: 2026-03-12 13:24:38.314299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77846ec918bd'
down_revision: Union[str, Sequence[str], None] = 'b4f2ada8ae10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
