"""Add assigned_employee_id to ClientProfile

Revision ID: b4f2ada8ae10
Revises: e8b0e1c64a7e
Create Date: 2026-03-12 13:13:34.904465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f2ada8ae10'
down_revision: Union[str, Sequence[str], None] = 'e8b0e1c64a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
