"""add aadhar and passport fields to client

Revision ID: c1cfad5b9ba8
Revises: 596a3d687fbe
Create Date: 2026-03-13 15:57:36.299766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cfad5b9ba8'
down_revision: Union[str, Sequence[str], None] = '596a3d687fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('aadhar_number', sa.String(length=12), nullable=True))
    op.add_column('clients', sa.Column('passport_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'passport_number')
    op.drop_column('clients', 'aadhar_number')
    # ### end Alembic commands ###
