"""add_compliance_fields_to_clients_final

Revision ID: d2ba705a30b4
Revises: 77846ec918bd
Create Date: 2026-03-12 14:27:14.160323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ba705a30b4'
down_revision: Union[str, Sequence[str], None] = '77846ec918bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('pan_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('residential_status', sa.String(length=100), nullable=False),
    sa.Column('tax_residency', sa.String(length=100), nullable=False),
    sa.Column('pep_status', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=False),
    sa.Column('mother_name', sa.String(length=255), nullable=False),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('income_source', sa.String(length=100), nullable=False),
    sa.Column('fatca_compliance', sa.String(length=100), nullable=False),
    sa.Column('existing_portfolio_value', sa.Float(), nullable=False),
    sa.Column('existing_portfolio_composition', sa.Text(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_branch', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('demat_account_number', sa.String(length=100), nullable=True),
    sa.Column('trading_account_number', sa.String(length=100), nullable=True),
    sa.Column('risk_profile', sa.String(length=100), nullable=False),
    sa.Column('investment_experience', sa.String(length=100), nullable=False),
    sa.Column('investment_objectives', sa.Text(), nullable=False),
    sa.Column('investment_horizon', sa.String(length=100), nullable=False),
    sa.Column('liquidity_needs', sa.String(length=100), nullable=False),
    sa.Column('advisor_name', sa.String(length=255), nullable=False),
    sa.Column('advisor_registration_number', sa.String(length=100), nullable=False),
    sa.Column('client_date', sa.Date(), nullable=False),
    sa.Column('nominee_name', sa.String(length=255), nullable=True),
    sa.Column('nominee_relationship', sa.String(length=100), nullable=True),
    sa.Column('previous_advisor_name', sa.String(length=255), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('declaration_signed', sa.Boolean(), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=True),
    sa.Column('client_signature_path', sa.String(length=512), nullable=True),
    sa.Column('advisor_signature_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_employee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employee_details.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index(op.f('ix_clients_email_normalized'), 'clients', ['email_normalized'], unique=True)
    op.create_table('client_audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_documents')
    op.drop_table('client_audit_trail')
    op.drop_index(op.f('ix_clients_email_normalized'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
