import uuid
import secrets
from datetime import datetime
from typing import Optional
from sqlalchemy import String, Boolean, DateTime, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID

from app.database.base import Base
from app.core.timezone import get_now_ist


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    subdomain: Mapped[str | None] = mapped_column(String(255), unique=True, nullable=True, index=True)
    custom_domain: Mapped[str | None] = mapped_column(String(255), unique=True, nullable=True, index=True)
    billing_plan: Mapped[str] = mapped_column(String(50), default="free")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_profile_completed: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    # ── Bridge Architecture Fields ──────────────────────────────────
    # The URL where this tenant's Bridge is reachable (e.g. https://bridge.bunty.com)
    bridge_url: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)

    # One-time token generated by Super Admin, used by the Bridge to register itself
    bridge_registration_token: Mapped[Optional[str]] = mapped_column(
        String(128), nullable=True, unique=True, index=True
    )

    # Shared secret used for ongoing authenticated communication between Backend ↔ Bridge
    bridge_api_secret: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Bridge lifecycle status
    bridge_status: Mapped[str] = mapped_column(
        String(20), default="PENDING", server_default="PENDING"
    )  # PENDING → REGISTERED → ACTIVE → OFFLINE → REVOKED

    bridge_registered_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    bridge_last_heartbeat: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # ── Billing / Client-Count Enforcement ──────────────────────────
    max_client_permit: Mapped[int] = mapped_column(Integer, default=5, server_default="5")
    current_client_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0")

    # ── Plan & Subscription ─────────────────────────────────────────
    plan_expiry_date: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    pricing_model: Mapped[str] = mapped_column(String(100), default="flat_fee") # e.g., per_user_yearly
    billing_mode: Mapped[str] = mapped_column(String(50), default="yearly") # e.g., monthly, quarterly, yearly

    # ── Timestamps ──────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # ── Helpers ─────────────────────────────────────────────────────
    @staticmethod
    def generate_bridge_token() -> str:
        """Generate a cryptographically secure registration token for a new Bridge."""
        return secrets.token_urlsafe(64)
